version: '2'

services:

  mysql_data:
    image: busybox
    volumes:
     - /var/lib/mysql

  mysql:
    image: mysql/mysql-server
    volumes_from:
     - mysql_data
    environment:
     - MYSQL_DATABASE=moodle
     - MYSQL_USER=moodle
     - MYSQL_ROOT_PASSWORD=moodle
    depends_on:
     - mysql_data

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MOODLE_VERSION: $MOODLE_VERSION
    depends_on:
     - mysql
    links:
     - mysql
    ports:
     - "8080:80"
    environment:
     - MOODLE_URL=$MOODLE_URL

